### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by arnexa** [splitbrain/dokuwiki-plugin-gallery#176] opened 2023-09-11 10:59 UTC
Message after update:
Error: Call to a member function getDataFromParams() on null
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the gallery plugin.
More info has been written to the DokuWiki error log.

error log:
2023-09-11 10:48:09	/var/www/dokuwiki/lib/plugins/gallery/action/prosemirror.php(47)	Error: Call to a member function getDataFromParams() on null
  #0 /var/www/dokuwiki/inc/Extension/EventHandler.php(80): action_plugin_gallery_prosemirror->writeDefaultsToJSINFO()
  #1 /var/www/dokuwiki/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
  #2 /var/www/dokuwiki/inc/Extension/Event.php(132): dokuwiki\Extension\Event->advise_before()
  #3 /var/www/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
  #4 /var/www/dokuwiki/doku.php(120): dokuwiki\Extension\Event::createAndTrigger()
  #5 {main}

**Comment by arnexa** [comment] 2023-09-11 11:01
Current release 2023-04-04a "Jack Jackrum"

**Comment by splitbrain** [comment] 2023-09-11 11:10
duplicate of #169

**Closed by splitbrain** 2023-09-11 11:10 UTC
