### ISSUE TITLE
Wish: multiple galleries on one page

### ISSUE THREAD

**Issue by eilko** [splitbrain/dokuwiki-plugin-gallery#91] opened 2016-11-18 07:32 UTC
it is now possible to add multiple galleries on one page, but they are somehow combined when viewing them. When you open the first set of images in the lightbox it will continue with the next set (gallery) on the same page. 

When you add special options like pagination, it can only be applied to one of the galleries on the page. If you add it to e.g. two galleries the second gallery will show the pagination buttons but iniatially no images.

Would like to see that like be able to add multiple galleries on one dokuwiki page as seperate galleries with each their own set of properties.

**Comment by Laynee** [comment] 2017-03-17 12:30
Yes, pagination is broken when there is more than one gallery in a page. See #81. I hope it will be fixed because I often use several galleries on a page and it takes a lot of screen space. So that's precisely when pagination is really needed that it does not work, it's kind of frustrating.

@splitbrain Hey Andy, can we have some feedback on this? Is it hard to fix?

**Comment by splitbrain** [comment] 2017-03-17 21:35
it's probably not super hard to fix. I just don't know when I will have time to look into it

**Comment by Laynee** [comment] 2017-03-19 15:04
Thank you, it's good to know that it's not a design flaw or something that cannot be fixed without major rewriting. Hope you'll get some time !

**Comment by splitbrain** [comment] 2023-08-23 18:33
Pagination is fixed.  I consider being able to browse through all images on a page, even when they come from different galleries a feature, not a bug.

**Closed by splitbrain** 2023-08-23 18:33 UTC
